name: Deploy BoltCMS to Vimexx

on:
  workflow_call:
    inputs:
      hostname:
        required: true
        type: string
      username:
        required: true
        type: string
      domainName:
        required: true
        type: string
    secrets:
      sshKey:
        required: true

jobs:
  deploy-updated-site:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ inputs.hostname }}
          username: ${{ inputs.username }}
          port: 7685
          key: ${{ secrets.sshKey }}
          script: |
            cd ~/domains/${{ inputs.domainName }}
            [[ -e "composer.phar" ]] || wget -O composer.phar https://getcomposer.org/composer-stable.phar
            php composer.phar self-update --2

            git reset --hard HEAD
            git pull --prune

            rm -rf var/cache/*
            php composer.phar install --no-progress --prefer-dist --optimize-autoloader --classmap-authoritative
            php bin/console doctrine:schema:update --force
            php bin/console doctrine:migrations:migrate --no-interaction
